export default {
	Draw: 'draw',
	EntityCollide: 'entityCollide',
	Pause: 'gamePause',
	PlayerComplete: 'trackComplete',
	PlayerFocusChange: 'playerFocusChange',
	PlayerFocusLost: 'playerFocusLost',
	RecorderStart: 'recorderStart',
	RecorderStop: 'recorderStop',
	ReplayAdd: 'replayAdd',
	ReplayEnd: 'replayEnd',
	ReplayStart: 'replayStart',
	Reset: 'reset',
	SettingsChange: 'settingsChange',
	StateChange: 'stateChange',
	Stats: 'stats',
	Tick: 'tick',
	ToolSelectionChange: 'toolSelectionChange',
	Unpause: 'gameUnpause'
}